services:
  - type: web
    name: rs-store-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
    autoDeploy: true
